name: Release Build
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking version
        id: version
        run: |
          echo ::set-output name=release::$(cat module.prop | grep version= | awk -F'=' '{print $2}')
          echo ::set-output name=releaseCode::$(cat module.prop | grep versionCode= | awk -F'=' '{print $2}')
      - name: Build
        run: zip -r Bash_For_Android_${{ steps.version.outputs.release}}.zip ./ -x '*.git*' -x '*.md' -x '*.json'
      - name: Delete tag ${{ steps.version.outputs.release}} if exists
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Release
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.version.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: JeelsBoobz/action-gh-release@v2
        if: success()
        with:
          tag_name: ${{ steps.version.outputs.release}}
          files: ./*.zip
          draft: false
          generate_release_notes: true
